### ISSUE TITLE
Setup IBC relayer for testnet

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#156]
In order to give a testnet a IBC tesing evnironment. We will setup relayer between likecoin-public-testnet-4 with osmosis testnet.

**Comment by mitchellchou** [comment]
@Rico-Wong Please review this doc https://www.notion.so/oursky/LIKE-OSMO-Relayer-Setup-43f75776cc094b38a880fe1cb68cc966

**Comment by rickmak** [comment]
Follow channel created.

```
  likeosmo:
    src:
      chain-id: likecoin-public-testnet-5
      client-id: 07-tendermint-0
      connection-id: connection-1
      channel-id: channel-1
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    dst:
      chain-id: osmo-test-4
      client-id: 07-tendermint-1871
      connection-id: connection-1472
      channel-id: channel-239
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    strategy:
      type: naive
  osmolike:
    src:
      chain-id: osmo-test-4
      client-id: 07-tendermint-1870
      connection-id: connection-1471
      channel-id: channel-238
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    dst:
      chain-id: likecoin-public-testnet-5
      client-id: 07-tendermint-0
      connection-id: connection-0
      channel-id: channel-0
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    strategy:
      type: naive

```

transaction in action: https://likecoin-public-testnet-5.oursky.dev/cosmos/tx/v1beta1/txs/B0ED21C8828C40E1CC221F690333BD358806284EF0A70E3439AB6515A69106EF
